### Testar o Ping
GET http://localhost:3000/ping
### Listar todas as Quests
GET http://localhost:3000/quests
### Obter Quest por ID
GET http://localhost:3000/quests/1
### Criar uma Nova Quest
POST http://localhost:3000/quests
Content-Type: application/json

{
  "title":"Minha Nova Quest",
  "description":"Esse é um teste de API no método POST",
  "xp":100,
  "difficulty":"Meio dificil"
}

### Testar o PUT
PUT http://localhost:3000/quests/2
Content-Type: application/json

{
  "title": "Put testado",
  "description": "Esse é um teste de API com o método PUT",
  "difficulty": "GG easy"
}

### Testar o endpoint /quests/:id/complete
PUT  http://localhost:3000/quests/2/complete

### Testar o DELETE
DELETE http://localhost:3000/quests/1

### Testar o filtro no GET
GET http://localhost:3000/quests?difficulty=easy

### Testar a paginação do GET
GET http://localhost:3000/quests?page=1&limit=3

### Testar paginação e filtro "completed" no GET
GET http://localhost:3000/quests?completed=true&page=1&limit=3
